# Generated by Django 4.1.7 on 2024-10-06 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Poeducto',
            new_name='Producto',
        ),
    ]
